export const data = [
  {
    number: 1,
    name: "Python-Django-Blog-App",
    image: "/static/img/pythonblogapp.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://hidden-gorge-57276.herokuapp.com/",
  },
  {
    number: 2,
    name: "React-Blog-App",
    image: "/static/img/reactblogapp.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-reactblog-app.netlify.app/",
  },
  {
    number: 3,
    name: "Reaact-Movi-App",
    image: "/static/img/reactmovieapp.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-movi-app.netlify.app/",
  },

  {
    number: 4,
    name: "Paython-Django-Todo-App",
    image: "/static/img/pythontodoapp.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://blooming-wave-32056.herokuapp.com/login",
  },
  {
    number: 5,
    name: "Python-Django-Weather-App",
    image: "/static/img/pythonweatherapp",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://enigmatic-coast-28265.herokuapp.com/",
  },
  {
    number: 6,
    name: "JavaScript-Calculator",
    image: "/static/img/javascriptcalculator.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-javascript-calculatorr.netlify.app/",
  },
  {
    number: 7,
    name: "React-Expence-Tracker",
    image: "/static/img/reactexpencetracker.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-expence-tracker.netlify.app/",
  },
  {
    number: 8,
    name: "React-Todo-App",
    image: "/static/img/reacttodoapp.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-todoappp.netlify.app/",
  },
  {
    number: 9,
    name: "React-Task-Tracker",
    image: "/static/img/reacttacktracker.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-first-react-todoapp.netlify.app/",
  },
  {
    number: 10,
    name: "React-Tour-App",
    image: "/static/img/reacttour.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-tour-app.netlify.app/",
  },
  {
    number: 11,
    name: "HTML-CSS-WebPage",
    image: "/static/img/htmlcssweb.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-html-css-webpage.netlify.app/",
  },
  {
    number: 10,
    name: "JavaScript-Free-Meal-app",
    image: "/static/img/javascriptcalculator.png",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-javascript-freemealapp.netlify.app/",
  },
];
