export const Projects = [
  {
    number: 1,
    name: "Python-Django-Blog-App",
    image: "../img/django-blogapp.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://hidden-gorge-57276.herokuapp.com/",
  },
  {
    number: 2,
    name: "React-Blog-App",
    image: "../img/react-blog.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-reactblog-app.netlify.app/",
  },
  {
    number: 3,
    name: "Reaact-Movi-App",
    image: "../img/react-blog.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-movi-app.netlify.app/",
  },

  {
    number: 4,
    name: "Paython-Django-Todo-App",
    image: "../img/django-todo.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://blooming-wave-32056.herokuapp.com/login",
  },
  {
    number: 5,
    name: "Python-Django-Weather-App",
    image: "../img/python-django-weatherapp.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://enigmatic-coast-28265.herokuapp.com/",
  },
  {
    number: 6,
    name: "JavaScript-Calculator",
    image: "../img/calculator.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-javascript-calculatorr.netlify.app/",
  },
  {
    number: 7,
    name: "React-Expence-Tracker",
    image: "../img/expence-tracker.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-expence-tracker.netlify.app/",
  },
  {
    number: 8,
    name: "React-Todo-App",
    image: "../img/todo1.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-todoappp.netlify.app/",
  },
  {
    number: 9,
    name: "React-Task-Tracker",
    image: "../img/todo2.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-first-react-todoapp.netlify.app/",
  },
  {
    number: 10,
    name: "React-Tour-App",
    image: "./img/react-tour.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-react-tour-app.netlify.app/",
  },
  {
    number: 11,
    name: "HTML-CSS-WebPage",
    image: "./img/html-css-webpage.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-html-css-webpage.netlify.app/",
  },
  {
    number: 10,
    name: "JavaScript-Free-Meal-app",
    image: "./img/js-freemeal.jpeg",
    desc: "aaaaaaaaaaaaaaaaaaaaaaa",
    url: "https://my-javascript-freemealapp.netlify.app/",
  },
];
